name: Test
on:
  workflow_dispatch:
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      pr_branch: test/${{ github.ref_name }}
      base_branch: ${{ github.ref_name }}
      run_id: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - run: |
          git branch -D "$pr_branch" || echo "No existing test branch found"
          git switch -c "$pr_branch"
      - run: |
          echo "$run_id" >> runs.txt
          git add runs.txt
          git commit -m "Add run $run_id"
          echo "Pushing to branch $pr_branch"
          git push --set-upstream origin "$pr_branch"
      - run: |
          PR="$(gh pr create --base "$base_branch" --fill)"
          gh pr merge "$PR" --rebase --delete-branch

